const base = '备忘录图片/';
const days = [
  {date:'9.25',dow:'周五',city:'广州 → 香港',en:'GUANGZHOU → HONG KONG',title:'高铁 · 前往香港',enTitle:'HIGH-SPEED RAIL TO HONG KONG',summary:'晚上从广州南乘坐 G6531 前往香港西九龙，为第二天飞往墨尔本做准备。',summaryEn:'Take G6531 from Guangzhou South to Hong Kong West Kowloon in the evening, preparing for tomorrow’s flight to Melbourne.',items:[['19:37','广州南出发','G6531 · High-speed rail'],['20:38','抵达香港西九龙','Guangzhou South → Hong Kong West Kowloon'],['晚上','香港住宿 / 休息','为 9 月 26 日国际航班预留充足时间']],places:[['广州南站','出发站 · Guangzhou South Railway Station','https://www.google.com/maps/search/?api=1&query=Guangzhou+South+Railway+Station'],['香港西九龙站','到达站 · Hong Kong West Kowloon Station','https://www.google.com/maps/search/?api=1&query=Hong+Kong+West+Kowloon+Station']],notes:['车次：G6531；出发时间 19:37，抵达时间 20:38。','截图中的乘车人姓名已打码，公开网页不会展示个人姓名。'],images:['925 去香港高铁.jpg']},

  {date:'9.26',dow:'周六',city:'墨尔本 / 吉朗',en:'MELBOURNE / GEELONG',title:'初抵墨尔本 · 海湾相见',enTitle:'ARRIVAL, DRIVE & BAY SUNSET',summary:'Chenyang 抵达墨尔本后取车，前往吉朗入住；下午休息，傍晚沿海滨散步，轻松开启澳洲旅程。',summaryEn:'Chenyang arrives in Melbourne, picks up the car and drives to Geelong for a gentle first evening by the bay.',items:[['00:20','Chenyang 从香港起飞','CX105 · Hong Kong → Melbourne'],['11:15','Chenyang 抵达墨尔本 T2','CX105 · Hong Kong → Melbourne'],['中午','机场取车','取车后前往吉朗，先办理入住'],['下午','Crown Plaza Geelong','33 Smythe Street · check-in / 休息'],['傍晚','Geelong Waterfront','沿海滨散步；体力充足再安排日落观景']],places:[['Melbourne Airport T2','航班抵达 · 取车','https://www.google.com/maps/search/?api=1&query=Melbourne+Airport+Terminal+2'],['Crown Plaza Geelong by IHG','住宿 · 33 Smythe Street, Geelong','https://www.google.com/maps/search/?api=1&query=Crowne+Plaza+Geelong+33+Smythe+Street'],['Geelong Waterfront','海滨散步 / 日落','https://www.google.com/maps/search/?api=1&query=Geelong+Waterfront'],['Eastern Beach Reserve','海边散步建议','https://www.google.com/maps/search/?api=1&query=Eastern+Beach+Reserve+Geelong'],['Cunningham Pier','海湾风景建议','https://www.google.com/maps/search/?api=1&query=Cunningham+Pier+Geelong']],notes:['Chenyang 航班：CX105，9 月 26 日 00:20 从香港起飞，11:15 抵达墨尔本 T2。','取车后直接前往吉朗，建议先入住 Crown Plaza Geelong，再决定是否去市区或海边。','实用 Tip：国际航班抵达后先处理电话卡、取车和补水；长途飞行当天不要排太满，停车和酒店入住留出余量。','风景建议：Geelong Waterfront 适合第一天轻松散步；Eastern Beach 和 Cunningham Pier 适合看海、吹风、拍照。'],images:['9.26-1.jpg','9.26-2.jpg','9.26-3.jpg','9.26-4.jpg','9.26-5.jpg']},
  {date:'9.27',dow:'周日',city:'大洋路',en:'GREAT OCEAN ROAD',title:'洛恩 · 十二使徒',enTitle:'LORNE & THE TWELVE APOSTLES',summary:'取车后在吉朗汇合，途经 Torquay、Bells Beach、Aireys Inlet，傍晚抵达十二使徒看日落，夜宿阿波罗湾。',summaryEn:'Pick up the car, meet in Geelong, cruise the coast and catch sunset at the Twelve Apostles before returning to Apollo Bay.',items:[['09:00','墨尔本市区取车','Shop 10, 99 Spencer St · 租车信息待核对'],['10:30','吉朗镇汇合','Meet up in Geelong'],['12:30','抵达洛恩小镇','午餐 · 停留休息'],['14:00','前往十二使徒','途经 Teddy’s Lookout / Kennett River'],['17:50','十二使徒日落','17:15 前到停车场 · 18:30–18:55 观晚霞'],['19:00','返回阿波罗湾','车程约 1.5 小时 · 民宿做饭']],places:[['Melbourne City Car Rental','取车 · Shop 10, 99 Spencer St','https://www.google.com/maps/search/?api=1&query=99+Spencer+Street+Melbourne'],['Lorne','午餐 / 休息','https://www.google.com/maps/search/?api=1&query=Lorne+Victoria+Australia'],['Twelve Apostles','日落观景','https://www.google.com/maps/search/?api=1&query=Twelve+Apostles+Victoria'],['45 Hickeys Cutting, Skenes Creek','住宿 · 阿波罗湾','https://www.google.com/maps/search/?api=1&query=45+Hickeys+Cutting+Skenes+Creek+VIC+3233']],notes:['晚上在民宿做饭，可在墨尔本提前准备食材。民宿下午可能需要提前 check-in。','沿途海岸线景观丰富，注意预留停车和拍照时间。'],images:['9.27-1.jpg','9.27-2.jpg','9.27-3.jpg','9.27-4.jpg','9.27-5.jpg','9.27-6.jpg']},
  {date:'9.28',dow:'周一',city:'大洋路 → 霍巴特',en:'GREAT OCEAN ROAD → HOBART',title:'返程 · 飞往塔州',enTitle:'BACK TO MELBOURNE & FLY TO TASMANIA',summary:'上午在阿波罗湾或 Colac 从容收尾，下午返回墨尔本机场；晚上乘 21:10 航班飞往霍巴特。',summaryEn:'Enjoy a relaxed morning, return the car at Melbourne Airport and take the 21:10 flight to Hobart.',items:[['上午','方案一：野生动物团','Apollo Bay Wildlife Wonders · 约 75 分钟 · 临时订票'],['上午','方案二：阿波罗湾逛逛','海鲜午餐比较有名'],['中午','Colac 小镇午餐','休息后继续返程'],['18:30','抵达墨尔本机场','还车、办理值机并托运行李'],['21:10','墨尔本飞往霍巴特','VA1334 · MEL T3 → HBA D · 预计 22:30 抵达']],places:[['Apollo Bay Wildlife Wonders','野生动物团 · 需提前确认','https://www.google.com/maps/search/?api=1&query=Wildlife+Wonders+Apollo+Bay'],['Colac','午餐 / 中途休息','https://www.google.com/maps/search/?api=1&query=Colac+Victoria+Australia'],['Melbourne Airport T3','还车 / 飞机 · 建议 18:30 到达','https://www.google.com/maps/search/?api=1&query=Melbourne+Airport+Terminal+3'],['Hobart Airport','抵达 · 提车','https://www.google.com/maps/search/?api=1&query=Hobart+Airport']],notes:['航班：VA1334，9 月 28 日 21:10 从墨尔本机场 T3 出发，22:30 抵达霍巴特机场 D。','已按需要托运行李估算：建议 18:30 到达机场，距离起飞约 2 小时 40 分，留出还车、值机、托运和安检时间。','墨尔本机场还车后，先确认航站楼与值机柜台，再办理托运；不要把到机场时间压到 19:10 以后。'],images:['9.28-1.jpg','9.28-2.jpg']},
  {date:'9.29',dow:'周二',city:'霍巴特',en:'HOBART',title:'城市漫游 · 惠灵顿山',enTitle:'HOBART CITY & MOUNT WELLINGTON',summary:'半天在霍巴特市内逛吃，下午驱车登上惠灵顿山顶，俯瞰城市后前往 Triabunna。',summaryEn:'Explore Hobart at an easy pace, drive up Mount Wellington in the afternoon, then continue to Triabunna.',items:[['上午','霍巴特市内自由活动','可组队，也可自由安排'],['中午','市内逛 & 吃','City walk and lunch'],['16:00','前往惠灵顿山顶','路况不错 · 新手友好'],['傍晚','前往 Triabunna','车程约 1 小时']],places:[['Hobart','市内逛吃','https://www.google.com/maps/search/?api=1&query=Hobart+Tasmania'],['Mount Wellington / kunanyi','俯瞰城市','https://www.google.com/maps/search/?api=1&query=Mount+Wellington+Tasmania'],['Triabunna','住宿 · 精确地址待补充','https://www.google.com/maps/search/?api=1&query=Triabunna+Tasmania']],notes:['今晚住 Triabunna，方便第二天早上前往玛丽亚岛。住宿精确地址待补充。'],images:['9.29-1.jpg']},
  {date:'9.30',dow:'周三',city:'玛丽亚岛',en:'MARIA ISLAND',title:'袋熊 · Painted Cliffs',enTitle:'MARIA ISLAND NATIONAL PARK',summary:'乘船约 30 分钟登岛，骑自行车探索 Painted Cliffs、Fossil Cliffs，沿途寻找袋熊和袋鼠。',summaryEn:'Take a 30-minute ferry to Maria Island, cycle between Painted Cliffs and Fossil Cliffs, and meet the island’s wombats and wallabies.',items:[['08:30','前往玛丽亚岛码头','船程约 30 分钟 · 岛上已定自行车'],['上午','登岛后骑车探索','根据船次灵活安排路线'],['中午','Painted Cliffs / Fossil Cliffs','带好午餐和水 · 岛上没有商店'],['14:30','乘船返程','回到码头可吃冰淇淋']],places:[['Encounter Maria Island Ferry','码头 / 船票','https://www.google.com/maps/search/?api=1&query=Encounter+Maria+Island+Triabunna'],['Painted Cliffs','海岸悬崖','https://www.google.com/maps/search/?api=1&query=Painted+Cliffs+Maria+Island'],['Fossil Cliffs','徒步 / 海岸','https://www.google.com/maps/search/?api=1&query=Fossil+Cliffs+Maria+Island'],['Triabunna','住宿 · 精确地址待补充','https://www.google.com/maps/search/?api=1&query=Triabunna+Tasmania']],notes:['岛上没有商店，务必自带午餐、水和好吃的。','如果坐 11:30 的船，建议先去左边看悬崖，中午光线更好；下午再去看袋熊。','船票链接：bookings.encountermaria.com.au'],images:['9.30-1.jpg','9.30-2.jpg','9.30-3.jpg','9.30-4.jpg','9.30-5.jpg','9.30-6.jpg','9.30-7.jpg']},
  {date:'10.1',dow:'周四',city:'朗塞斯顿',en:'LAUNCESTON',title:'公路 · 企鹅归巢',enTitle:'ROAD TRIP & PENGUIN WATCHING',summary:'从 Triabunna 出发，经 Campbell 午餐，下午抵达 Low Head，傍晚参加企鹅归巢团，夜宿朗塞斯顿。',summaryEn:'Drive from Triabunna via Campbell, arrive at Low Head in the afternoon, then join an evening penguin tour before staying in Launceston.',items:[['上午','Triabunna 出发','Drive north'],['中午','Campbell 午餐','中途用餐与休息'],['下午','抵达 Low Head','提前到达，准备企鹅团'],['傍晚','企鹅归巢','参加当地 guided tour'],['晚上','回朗塞斯顿','入住酒店 · 地址待补充']],places:[['Campbell Town','午餐 / 休息','https://www.google.com/maps/search/?api=1&query=Campbell+Town+Tasmania'],['Low Head Penguin Tours','企鹅归巢','https://www.google.com/maps/search/?api=1&query=Low+Head+Penguin+Tours'],['Launceston','住宿 · 精确地址待补充','https://www.google.com/maps/search/?api=1&query=Launceston+Tasmania']],notes:['企鹅归巢时间会随季节变化，请以当天 tour 通知为准。'],images:['10.1-1.jpg','10.1-2.jpg']},
  {date:'10.2',dow:'周五',city:'朗塞斯顿 → 悉尼',en:'LAUNCESTON → SYDNEY',title:'朗塞斯顿收尾 · 悉尼夜色',enTitle:'LAUNCESTON CITY WALK & FLY TO SYDNEY',summary:'上午在朗塞斯顿 citywalk，午餐后前往机场；15:40 起飞，抵达悉尼后入住北悉尼的 Citadines Walker North Sydney。',summaryEn:'Take a morning city walk, arrive at the airport early for baggage drop, then fly to Sydney and check in at Citadines Walker North Sydney.',items:[['上午','朗塞斯顿 citywalk','自由逛逛与拍照'],['中午','午餐','Lunch in Launceston'],['13:40','抵达朗塞斯顿机场','还车、值机并托运行李'],['15:40','朗塞斯顿飞往悉尼','QF1534 · LST → SYD · 预计 17:25 抵达'],['晚上','入住北悉尼','Citadines Walker North Sydney · 晚餐与休息']],places:[['Launceston Airport','还车 / 飞机 · 建议 13:40 到达','https://www.google.com/maps/search/?api=1&query=Launceston+Airport'],['Citadines Walker North Sydney','住宿 · 悉尼北区','https://www.google.com/maps/search/?api=1&query=Citadines+Walker+North+Sydney'],['Sydney Airport','抵达机场','https://www.google.com/maps/search/?api=1&query=Sydney+Airport']],notes:['航班：QF1534，10 月 2 日 15:40 从朗塞斯顿起飞，17:25 抵达悉尼。','已按需要托运行李估算：建议 13:40 到达朗塞斯顿机场，起飞前 2 小时办理还车、值机、托运和安检。','抵达悉尼后建议直接前往 Citadines Walker North Sydney，入住后再安排晚餐。'],images:['10.2-1.jpg','10.2-2.jpg','10.2-3.jpg','10.2-4.jpg','10.2-5.jpg','10.2-6.jpg']},
  {date:'10.3',dow:'周六',city:'悉尼',en:'SYDNEY',title:'城市漫游 · 购物',enTitle:'CITY WALK & SHOPPING',summary:'悉尼市内自由活动，可组队，也可以各自探索喜欢的街区、景点与商店。',summaryEn:'A flexible day in Sydney: explore together or split up for your favourite neighbourhoods, sights and shopping.',items:[['全天','悉尼 Citywalk','可组队 / 自由活动'],['下午','购物 & 咖啡','按兴趣灵活安排'],['晚上','自由晚餐','Meet up or dine independently']],places:[['Sydney CBD','市内漫游','https://www.google.com/maps/search/?api=1&query=Sydney+CBD+Australia'],['Queen Victoria Building','购物 / 建筑','https://www.google.com/maps/search/?api=1&query=Queen+Victoria+Building+Sydney'],['The Rocks','街区漫游','https://www.google.com/maps/search/?api=1&query=The+Rocks+Sydney']],notes:['悉尼酒店精确地址待补充。建议按天气与大家兴趣分组行动。'],images:['10.3-1.jpg','10.3-2.jpg','10.3-3.jpg','10.3-4.jpg']},
  {date:'10.4',dow:'周日',city:'悉尼',en:'SYDNEY',title:'观鲸 · 邦迪海滩',enTitle:'WHALE WATCHING & BONDI BEACH',summary:'早起前往 Darling Harbour 参加观鲸，下午去邦迪海滩游泳、徒步，享受悉尼海岸线。',summaryEn:'Start early for a whale-watching cruise from Darling Harbour, then swim and walk along Bondi Beach.',items:[['08:30–11:30','观鲸','King Street Wharf 6 · Darling Harbour'],['中午','返回市区','午餐与休息'],['下午','邦迪海滩','游泳 / 海岸徒步'],['晚上','返回酒店','注意安全与闹钟']],places:[['King Street Wharf 6','观鲸集合点 · Darling Harbour','https://www.google.com/maps/search/?api=1&query=King+Street+Wharf+6+Darling+Harbour+Sydney'],['Bondi Beach','游泳 / 徒步','https://www.google.com/maps/search/?api=1&query=Bondi+Beach+Sydney']],notes:['注意闹钟。观鲸集合点：King Street Wharf 6, Darling Harbour Sydney, NSW 2000。','海边活动注意防晒、海况与个人安全。'],images:['10.4-1.jpg']},
  {date:'10.5',dow:'周一',city:'悉尼 → 香港',en:'SYDNEY → HONG KONG',title:'返程 · 带着海风回家',enTitle:'SYDNEY TO HONG KONG',summary:'整理行李后前往悉尼机场，乘坐 CX162 返回香港，结束这场南半球漫游。',summaryEn:'Head to Sydney Airport and take CX162 back to Hong Kong, bringing this southern-hemisphere journey to a close.',items:[['08:00','前往悉尼机场','建议至少提前 3 小时到达，办理国际航班托运'],['11:10','悉尼飞往香港','CX162 · SYD T1 → HKG · 预计 17:45 抵达'],['17:45','抵达香港','Hong Kong International Airport']],places:[['Citadines Walker North Sydney','出发住宿 · 悉尼北区','https://www.google.com/maps/search/?api=1&query=Citadines+Walker+North+Sydney'],['Sydney Airport T1','国际航班 · 建议 08:00 出发','https://www.google.com/maps/search/?api=1&query=Sydney+Airport+Terminal+1'],['Hong Kong International Airport','抵达机场','https://www.google.com/maps/search/?api=1&query=Hong+Kong+International+Airport']],notes:['航班：CX162，10 月 5 日 11:10 从悉尼起飞，17:45 抵达香港；机型 Boeing 777-300ER。','国际航班需要托运行李，建议 08:00 左右从住宿出发，实际出发时间根据当天交通和航司要求调整。'],images:['10.5-1.jpg','10.5-2.jpg','10.5-3.jpg']}
];

const picker = document.querySelector('#day-picker');
const view = document.querySelector('#day-view');
const count = document.querySelector('#day-count');
count.textContent = `${days.length} DAYS`;
function render(index){
  const d=days[index];
  document.querySelectorAll('.day-button').forEach((b,i)=>b.classList.toggle('active',i===index));
  view.innerHTML=`<div class="day-header"><div><div class="day-label">DAY ${String(index+1).padStart(2,'0')} · ${d.date} ${d.dow}</div><h2 class="day-title">${d.title}</h2><p class="day-subtitle">${d.enTitle}<br>${d.city} · ${d.en}</p></div><div><p class="summary">${d.summary}<span>${d.summaryEn}</span></p></div></div><div class="detail-grid"><div class="details"><h3>行程细则 / DETAILS</h3><div class="timeline">${d.items.map(x=>`<div class="timeline-item"><time>${x[0]}</time><p>${x[1]}<small>${x[2]}</small></p></div>`).join('')}</div><div class="places"><h3>地点与导航 / PLACES & MAPS</h3>${d.places.map(x=>`<div class="place"><div>${x[0]}<small>${x[1]}</small></div><a class="map-link" target="_blank" rel="noopener" href="${x[2]}">地图 ↗</a></div>`).join('')}</div></div><div><div class="notes"><h3>旅行提醒 / NOTES</h3>${d.notes.map(n=>`<p>· ${n}</p>`).join('')}</div><div class="gallery"><h3>旅途灵感 / VISUAL NOTES</h3><div class="gallery-grid">${d.images.map(img=>`<img loading="lazy" src="${base}${img}" alt="${d.date} ${d.title}">`).join('')}</div></div></div></div>`;
  history.replaceState(null,'',`#${d.date.replace('.','-')}`);
}
days.forEach((d,i)=>{const b=document.createElement('button');b.className='day-button';b.innerHTML=`<strong>${d.date}</strong>${d.city}`;b.addEventListener('click',()=>render(i));picker.appendChild(b)});
const hash=location.hash.replace('#','');const initial=Math.max(0,days.findIndex(d=>d.date.replace('.','-')===hash));render(initial);
